packages:
  - durable-execution
  - durable-execution-orpc-utils
  - durable-execution-storage-test-utils
  - durable-execution-storage-drizzle
  - durable-execution-storage-convex
  - durable-execution-storage-convex/test

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver

catalogs:
  prod:
    '@gpahal/std': ^0.0.38
    '@standard-schema/spec': ^1.0.0
    '@standard-schema/utils': ^0.3.0
    nanoid: ^5.1.5
    superjson: ^2.2.2
    zod: ^4.1.5
  dev:
    '@changesets/cli': ^2.29.6
    '@edge-runtime/vm': ^5.0.0
    '@gpahal/eslint-config': ^0.0.119
    '@gpahal/prettier-config': ^0.0.32
    '@gpahal/std-node': ^0.0.36
    '@gpahal/tsconfig': ^0.0.20
    '@ianvs/prettier-plugin-sort-imports': ^4.7.0
    '@libsql/client': ^0.15.14
    '@orpc/client': ^1.8.6
    '@orpc/contract': ^1.8.6
    '@orpc/server': ^1.8.6
    '@testcontainers/mysql': ^11.5.1
    '@testcontainers/postgresql': ^11.5.1
    '@types/node': ^24.3.0
    '@types/pg': ^8.15.5
    '@vitest/coverage-v8': ^3.2.4
    convex: ^1.26.2
    drizzle-kit: ^0.31.4
    drizzle-orm: ^0.44.5
    eslint: ^9.34.0
    mysql2: ^3.14.4
    npm-run-all2: ^8.0.4
    pg: ^8.16.3
    premove: ^4.0.0
    prettier: ^3.6.2
    simple-git-hooks: ^2.13.1
    testcontainers: ^11.5.1
    tsup: ^8.5.0
    tsx: ^4.20.5
    turbo: ^2.5.6
    typedoc: ^0.28.12
    typedoc-plugin-mermaid: ^1.12.0
    typescript: ^5.9.2
    vitest: ^3.2.4
