name: Run tests and upload coverage

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.14.0'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install -r

      - name: Run tests
        run: pnpm test-coverage

      - name: Upload coverage for durable-execution to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./durable-execution/coverage/coverage-final.json
          flags: durable-execution

      - name: Upload coverage for storage-drizzle to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./storage-drizzle/coverage/coverage-final.json
          flags: storage-drizzle
